baseurl = "https://fe-dashboard.herokuapp.com/"
languageCode = "en-us"
title = "Dashboard"
theme = "Hugrid"
canonifyurls = true

[params]
  # Shown in the home page
  subtitle = "Front End Stack Dashboard"
  brand = "Dashboard"
